### ISSUE TITLE
Syntax Highlighting not working ST3

### ISSUE THREAD

**Issue by richarddavenport** [theoperatore/VashSyntaxDefinition#1]
Using Sublime Text 3 and the base Monokai theme and I'm only getting syntax highlighting for `@model`.
![rad 2014-11-13 at 9 55 37 am](https://cloud.githubusercontent.com/assets/3596012/5031330/b4d608f0-6b1b-11e4-906a-a555852fa777.png)

Can you help me out? Thanks!

**Comment by theoperatore** [comment]
Yeah I can help! I'll look into it today. I remember having a similar issue when first making the definition.

**Comment by theoperatore** [comment]
![screen shot 2014-11-13 at 2 43 21 pm](https://cloud.githubusercontent.com/assets/395178/5036214/7477f606-6b43-11e4-9c94-0d2d6a0e1a51.png)
![screen shot 2014-11-13 at 2 29 42 pm](https://cloud.githubusercontent.com/assets/395178/5036000/8f31c546-6b41-11e4-9b9e-e11d9518a2f6.png)

I just pushed a newer version of the syntax definition. If you could upgrade the package and let me know? It seems to be a problem with the scopes. just want to make sure that's the actual problem.

**Comment by richarddavenport** [comment]
Awesome! Thank you, that did it...
![rad 2014-11-13 at 10 31 03 pm](https://cloud.githubusercontent.com/assets/3596012/5041332/fd903f3e-6b84-11e4-9dfd-dc51f1c5aec5.png)
