### ISSUE TITLE
More syntax issues

### ISSUE THREAD

**Issue by richarddavenport** [theoperatore/VashSyntaxDefinition#2]
Sorry @theoperatore, I have another syntax issue. 

Here is HTML syntax:
![rad 2014-11-18 at 3 37 49 pm](https://cloud.githubusercontent.com/assets/3596012/5096660/b045daf0-6f39-11e4-9d86-ce31eb0c4150.png)

Here is VASH:
![rad 2014-11-18 at 3 38 19 pm](https://cloud.githubusercontent.com/assets/3596012/5096668/c4e7f36c-6f39-11e4-9e2d-d4bed8d46d0e.png)

Something wrong with putting a single tick in a comment:
![rad_2014-11-18_at_3_46_04_pm](https://cloud.githubusercontent.com/assets/3596012/5096769/99b489d4-6f3a-11e4-8980-46043f48e482.jpg)

I might go ahead and learn about syntax definitions and submit some pull requests. Would that be okay?

**Comment by theoperatore** [comment]
yup, totally ok. The help is appreciated. I think I know the fix for this specific problem, but I guess it'll happen again if you use a single quote without using a  `<text></text>` block to render any text via html.

**Comment by theoperatore** [comment]
Updated the definition again to handle `<!-- -->` properly. so you won't have an issue with single or double quotes in a comment, but you will still have an issue using a single/double quote inside any html tag that you want rendered plainly. For now, until either of us can fix it, if you do:

``` html
<p><text>This'll show 'em! Quotes definitely work now</text></p>
```

You won't have a syntax problem.

**Comment by richarddavenport** [comment]
Great! Thanks for the update!

**Comment by ilyabreev** [comment]
I still have an issue with single quote inside html tag.
![2015-02-08 12 56 46](https://cloud.githubusercontent.com/assets/1045399/6096129/471de844-af92-11e4-908e-a9234e5f7256.png)
